{{- if not .Values.common.majorRelease }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.volume.name" (list . "" )}}-configmap
  labels: {{- include "common.application.labels" . | nindent 4 }}
data:
  ENV: {{ .Values.common.application.env }}
  application.yml: |-
    CONNECT_TIME_OUT: {{ .Values.config.connectTimeout }}
    READ_TIME_OUT: {{ .Values.config.readTimeout }}
    spring:
      application:
        name: {{ include "common.volume.name" (list . "" )}}
      mvc:
        pathmatch:
          matching-strategy: ant_path_matcher
    management:
      endpoints:
        web:
          exposure:
            include: health,metrics,prometheus
      metrics:
        tags:
          application: ${spring.application.name}
{{- end}} 
